### ISSUE TITLE
Add likes

### ISSUE THREAD

**Issue by gannetson** [pony-revolution/helpothers#40]
Add likes.

1. Add a Like model (listings app) with generic foreign key to a model and a foreign key to user also
2. Make sure a user can only vote once for a certain object.
3. Add views to add a vote for a Resource
4. redirect to login if user is not loged in.
5. Add a Like button (or Liked string) to Resource Detail page

**Comment by jonathanzerox** [comment]
I am working on it... i've already cloned the project and started creating models...

**Comment by gannetson** [comment]
Cool @jonathanzerox. Nice to have you on board.

**Comment by jonathanzerox** [comment]
@gannetson should i display how many likes a resource has(either in the details view, or in the resources listing page)

**Comment by zanderle** [comment]
Personally, I think we don't need to show how many likes a resource has - we can just use it for ordering...

**Comment by jonathanzerox** [comment]
almost done, except i don't know where to place the view for the resource, if possible you can we can i.m on skype(jonathanzerox)

**Comment by zanderle** [comment]
@jonathanzerox you can place the view for the resource in `listings` app. More specifically, `listings.views`

**Comment by bartleijssenaar** [comment]
Hi @gannetson! Can you close the issue? This way the payment gets triggered.
